if (isServer) then {
 
_vehicle_5 = objNull;
if (true) then
{
  _this = createVehicle ["MAP_A_Castle_Wall1_20", [6940.1445, 11431.345, -1.6219094], [], 0, "CAN_COLLIDE"];
  _vehicle_5 = _this;
  _this setDir 92.389053;
  _this setPos [6940.1445, 11431.345, -1.6219094];
};
 
_vehicle_6 = objNull;
if (true) then
{
  _this = createVehicle ["MAP_A_Castle_Wall1_20", [6935.8115, 11462.663, -3.6548748], [], 0, "CAN_COLLIDE"];
  _vehicle_6 = _this;
  _this setDir 71.570549;
  _this setPos [6935.8115, 11462.663, -3.6548748];
};
 
_vehicle_7 = objNull;
if (true) then
{
  _this = createVehicle ["MAP_A_Castle_Wall1_20", [6938.0483, 11450.827, -3.3339789], [], 0, "CAN_COLLIDE"];
  _vehicle_7 = _this;
  _this setDir 82.330101;
  _this setPos [6938.0483, 11450.827, -3.3339789];
};
 
_vehicle_8 = objNull;
if (true) then
{
  _this = createVehicle ["MAP_A_Castle_Wall1_20", [6941.4946, 11412.072, -1.8531784], [], 0, "CAN_COLLIDE"];
  _vehicle_8 = _this;
  _this setDir 73.874512;
  _this setPos [6941.4946, 11412.072, -1.8531784];
};
 
_vehicle_9 = objNull;
if (true) then
{
  _this = createVehicle ["MAP_A_Castle_Wall1_20", [6906.606, 11505.717, -0.77154428], [], 0, "CAN_COLLIDE"];
  _vehicle_9 = _this;
  _this setDir 53.512135;
  _this setPos [6906.606, 11505.717, -0.77154428];
};
 
_vehicle_10 = objNull;
if (true) then
{
  _this = createVehicle ["MAP_A_Castle_Wall1_20", [6842.3438, 11446.435, 1.8992796], [], 0, "CAN_COLLIDE"];
  _vehicle_10 = _this;
  _this setDir 80.053925;
  _this setPos [6842.3438, 11446.435, 1.8992796];
};
 
_vehicle_11 = objNull;
if (true) then
{
  _this = createVehicle ["MAP_A_Castle_Wall1_20", [6843.0483, 11433.395, 6.1035156e-005], [], 0, "CAN_COLLIDE"];
  _vehicle_11 = _this;
  _this setDir 77.754898;
  _this setPos [6843.0483, 11433.395, 6.1035156e-005];
};
 
_vehicle_12 = objNull;
if (true) then
{
  _this = createVehicle ["MAP_A_Castle_Wall1_20", [6859.0854, 11399.583, -3.0517578e-005], [], 0, "CAN_COLLIDE"];
  _vehicle_12 = _this;
  _this setDir 52.922298;
  _this setPos [6859.0854, 11399.583, -3.0517578e-005];
};
 
_vehicle_13 = objNull;
if (true) then
{
  _this = createVehicle ["MAP_A_Castle_Wall1_20", [6869.0601, 11386.499, -0.79708982], [], 0, "CAN_COLLIDE"];
  _vehicle_13 = _this;
  _this setDir 52.531345;
  _this setPos [6869.0601, 11386.499, -0.79708982];
};
 
_vehicle_14 = objNull;
if (true) then
{
  _this = createVehicle ["MAP_A_Castle_Wall1_20", [6914.0522, 11415.596, 9.1552734e-005], [], 0, "CAN_COLLIDE"];
  _vehicle_14 = _this;
  _this setDir 91.984665;
  _this setPos [6914.0522, 11415.596, 9.1552734e-005];
};
 
_vehicle_15 = objNull;
if (true) then
{
  _this = createVehicle ["MAP_A_Castle_Wall1_20", [6878.3696, 11414.688], [], 0, "CAN_COLLIDE"];
  _vehicle_15 = _this;
  _this setDir 65.02018;
  _this setPos [6878.3696, 11414.688];
};
 
_vehicle_16 = objNull;
if (true) then
{
  _this = createVehicle ["MAP_A_Castle_Wall1_20", [6871.916, 11433.019, 1.7573966], [], 0, "CAN_COLLIDE"];
  _vehicle_16 = _this;
  _this setDir 73.71463;
  _this setPos [6871.916, 11433.019, 1.7573966];
};
 
_vehicle_17 = objNull;
if (true) then
{
  _this = createVehicle ["MAP_A_Castle_Wall1_20", [6868.77, 11451.207, -0.40283322], [], 0, "CAN_COLLIDE"];
  _vehicle_17 = _this;
  _this setDir 80.582947;
  _this setPos [6868.77, 11451.207, -0.40283322];
};
 
_vehicle_18 = objNull;
if (true) then
{
  _this = createVehicle ["MAP_A_Castle_Wall1_20", [6915.5054, 11446.038, 9.1552734e-005], [], 0, "CAN_COLLIDE"];
  _vehicle_18 = _this;
  _this setDir -93.647102;
  _this setPos [6915.5054, 11446.038, 9.1552734e-005];
};
 
_vehicle_19 = objNull;
if (true) then
{
  _this = createVehicle ["MAP_A_Castle_Wall1_20", [6907.7563, 11463.254], [], 0, "CAN_COLLIDE"];
  _vehicle_19 = _this;
  _this setDir 47.505054;
  _this setPos [6907.7563, 11463.254];
};
 
_vehicle_20 = objNull;
if (true) then
{
  _this = createVehicle ["MAP_A_Castle_Gate", [6906.5562, 11400.696, -3.0517578e-005], [], 0, "CAN_COLLIDE"];
  _vehicle_20 = _this;
  _this setDir -27.429035;
  _this setPos [6906.5562, 11400.696, -3.0517578e-005];
};
 
_vehicle_21 = objNull;
if (true) then
{
  _this = createVehicle ["MAP_A_Castle_Wall1_20", [6880.8247, 11469.32, 3.0517578e-005], [], 0, "CAN_COLLIDE"];
  _vehicle_21 = _this;
  _this setDir -4.1842742;
  _this setPos [6880.8247, 11469.32, 3.0517578e-005];
};
 
};